object Versions {
    const val kotlinVersion = "1.5.30"
    const val hiltVersion = "2.38.1"
    const val timberVersion = "5.0.1"
    const val gsonVersion = "2.8.6"
    const val retrofitVersion = "2.9.0"
    const val lifecycleVersion = "2.3.1"
    const val navigationVersion = "2.3.5"
    const val coroutineVersion = "1.5.0"
    const val fragmentVersion = "1.3.6"
    const val roomVersion = "2.4.0-alpha04"
    const val coil_version = "1.3.2"
    const val kPermissionsVersion = "3.2.1"
    const val junitVersion = "1.1.3"
    const val mockkVersion = "1.12.0"
    const val junit5Version = "5.7.1"
}
